FROM solr:7.7-alpine

ARG SOLR_PORT=8983

# Copy solr config from the version used by eZ Platform
COPY --chown=solr:solr ./migrations/solr/ /opt/solr/server/solr/configsets/ez

# Prepare config
RUN cp -R /opt/solr/server/solr/configsets/_default/conf/lang /opt/solr/server/solr/configsets/ez \
 && cp /opt/solr/server/solr/configsets/_default/conf/solrconfig.xml /opt/solr/server/solr/configsets/ez \
 && cp /opt/solr/server/solr/configsets/_default/conf/stopwords.txt /opt/solr/server/solr/configsets/ez \
 && cp /opt/solr/server/solr/configsets/_default/conf/synonyms.txt /opt/solr/server/solr/configsets/ez \
 && cp /opt/solr/example/example-DIH/solr/solr/conf/currency.xml /opt/solr/server/solr/configsets/ez \
 && cp /opt/solr/server/solr/solr.xml /opt/solr/server/solr/configsets/ez \
 && sed -i.bak '/<updateRequestProcessorChain name="add-unknown-fields-to-the-schema">/,/<\/updateRequestProcessorChain>/d' /opt/solr/server/solr/configsets/ez/solrconfig.xml \
 && sed -ie 's/${solr.autoSoftCommit.maxTime:-1}/${solr.autoSoftCommit.maxTime:20}/' /opt/solr/server/solr/configsets/ez/solrconfig.xml

RUN precreate-core collection1 /opt/solr/server/solr/configsets/ez \
 && precreate-core econtent /opt/solr/server/solr/configsets/ez \
 && precreate-core econtent_back /opt/solr/server/solr/configsets/ez
