FROM solr:6.6.5-alpine

ARG SOLR_PORT=8983

# Copy solr config from the version used by eZ Platform
COPY vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/ /opt/solr/server/tmp

# Prepare config
RUN mkdir -p /opt/solr/server/ez/template \
 && cp -R /opt/solr/server/tmp/* /opt/solr/server/ez/template \
 && cp /opt/solr/server/solr/configsets/basic_configs/conf/currency.xml /opt/solr/server/ez/template \
 && cp /opt/solr/server/solr/configsets/basic_configs/conf/solrconfig.xml /opt/solr/server/ez/template \
 && cp /opt/solr/server/solr/configsets/basic_configs/conf/stopwords.txt /opt/solr/server/ez/template \
 && cp /opt/solr/server/solr/configsets/basic_configs/conf/synonyms.txt /opt/solr/server/ez/template \
 && cp /opt/solr/server/solr/configsets/basic_configs/conf/elevate.xml /opt/solr/server/ez/template \
 && cp /opt/solr/server/solr/solr.xml /opt/solr/server/ez \
 && sed -i.bak '/<updateRequestProcessorChain name="add-unknown-fields-to-the-schema">/,/<\/updateRequestProcessorChain>/d' /opt/solr/server/ez/template/solrconfig.xml \
 && sed -ie 's/${solr.autoSoftCommit.maxTime:-1}/${solr.autoSoftCommit.maxTime:20}/' /opt/solr/server/ez/template/solrconfig.xml

# Set our core config as home
ENV SOLR_HOME /opt/solr/server/ez

# Make sure cores are created on startup
RUN bin/solr -s ez -p $SOLR_PORT \
 && bin/solr create_core -c collection1 -d server/ez/template -p $SOLR_PORT \
 && bin/solr create_core -c econtent -d server/ez/template -p $SOLR_PORT \
 && bin/solr create_core -c econtent_back -d server/ez/template -p $SOLR_PORT

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["solr-foreground"]
