FROM solr:6.6-alpine

ARG SOLR_PORT=8983

# Copy solr config from the version used by eZ Platform
COPY vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/ /opt/solr/server/tmp

# Prepare config
RUN mkdir -p /opt/solr/server/ez/template \
 && cp -R /opt/solr/server/tmp/* /opt/solr/server/ez/template \
 && cp /opt/solr/server/solr/configsets/basic_configs/conf/currency.xml /opt/solr/server/ez/template \
 && cp /opt/solr/server/solr/configsets/basic_configs/conf/solrconfig.xml /opt/solr/server/ez/template \
 && cp /opt/solr/server/solr/configsets/basic_configs/conf/stopwords.txt /opt/solr/server/ez/template \
 && cp /opt/solr/server/solr/configsets/basic_configs/conf/synonyms.txt /opt/solr/server/ez/template \
 && cp /opt/solr/server/solr/configsets/basic_configs/conf/elevate.xml /opt/solr/server/ez/template \
 && cp /opt/solr/server/solr/solr.xml /opt/solr/server/ez \
 && sed -i.bak '/<updateRequestProcessorChain name="add-unknown-fields-to-the-schema">/,/<\/updateRequestProcessorChain>/d' /opt/solr/server/ez/template/solrconfig.xml \
 && sed -ie 's/${solr.autoSoftCommit.maxTime:-1}/${solr.autoSoftCommit.maxTime:20}/' /opt/solr/server/ez/template/solrconfig.xml

# Set our core config as home
ENV SOLR_HOME /opt/solr/server/ez

# Make sure cores are created on startup
RUN bin/solr -s ez -p "$SOLR_PORT" \
 && bin/solr create_core -c collection1 -d server/ez/template -p "$SOLR_PORT" \
 && bin/solr create_core -c econtent1 -d server/ez/template -p "$SOLR_PORT" \
 && bin/solr create_core -c econtent2 -d server/ez/template -p "$SOLR_PORT" \
 && wget -q -O /dev/null http://127.0.0.1:"$SOLR_PORT"/solr/admin/cores?action=RENAME\&core=econtent1\&other=econtent\&wt=json \
 && wget -q -O /dev/null http://127.0.0.1:"$SOLR_PORT"/solr/admin/cores?action=RENAME\&core=econtent2\&other=econtent_back\&wt=json
